- name: Laravel Deployment
  hosts: db
  remote_user: "{{ ansible_host_user }}"
  become: 'true'
  become_method: sudo
  vars_files:
    - vars/main.yml
  tasks:
    - name: Updating software repository
      apt:
         update_cache: yes
         upgrade: yes

    - name: Installing MYSQL 
      apt:
         name: ['mysql-server' , 'php{{php_version}}-mysql', 'python3-mysqldb', 'python3-pymysql' , 'python3-dev', 'python3',  'python3-pip']
         state: latest

    - name: Starting and Enabling mysql service
      service:
         name: mysql.service
         state: started
    
    - name: Setting db root user password
      mysql_user:
         name: root
         password: "{{ root_password }}"
         login_unix_socket: /var/run/mysqld/mysqld.sock
         state: present

    - name: Creating Prestashop database
      mysql_db:
         name: "{{ mysql_app_db }}"
         login_user: root
         login_password: "{{ root_password }}"
         login_unix_socket: /var/run/mysqld/mysqld.sock
         state: present

    - name: Creating Prestashop db-user
      mysql_user:
         name: "{{ mysql_app_user }}"
         login_user: root
         login_password: "{{ root_password }}"
         login_unix_socket: /var/run/mysqld/mysqld.sock
         password: "{{ mysql_app_user_password }}"
         priv: '*.*:ALL'
         state: present